language: python
sudo: false
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- pypy
- pypy3
install:
- pip install -r requirements/base.txt
- if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r requirements/py2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements/pypy2.txt; fi
- pip install -r requirements/tests.txt
- python setup.py install
script:
- py.test tests/unit/ --cov rps --cov scripts --cov-report term-missing
#- py.test tests/functional/
after_script:
- pep8 --show-source rps
after_success:
- coveralls
